# Generated by Django 4.1.1 on 2022-10-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
